apiVersion: serving.kserve.io/v1beta1
kind: InferenceService
metadata:
  name: soccer-results-predictor
  annotations:
    serving.kserve.io/deploymentMode: ModelMesh
spec:
  predictor:
    model:
      modelFormat:
        name: soccer-model
      runtime: soccer-runtime-0.x # OPTIONAL
      storage:
        key: localMinIO
        path: models/custom_fifa_model.py
