apiVersion: serving.kserve.io/v1beta1
kind: InferenceService
metadata:
  name: keras-example
  annotations:
    serving.kserve.io/deploymentMode: ModelMesh
spec:
  predictor:
    model:
      modelFormat:
        name: keras
      storage:
        key: localMinIO
        path: keras/mnist.h5